# Generated by Django 6.0.6 on 2026-06-17 12:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='学院名称')),
                ('short_name', models.CharField(blank=True, max_length=20, verbose_name='简称')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL标识')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '学院',
                'verbose_name_plural': '学院',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='类型名称')),
                ('slug', models.SlugField(unique=True, verbose_name='URL标识')),
                ('icon', models.CharField(blank=True, default='📄', max_length=20, verbose_name='图标')),
            ],
            options={
                'verbose_name': '资料类型',
                'verbose_name_plural': '资料类型',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='课程名称')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='课程代码')),
                ('course_type', models.CharField(choices=[('general', '通识课'), ('major', '专业课')], default='major', max_length=10, verbose_name='课程类型')),
                ('description', models.TextField(blank=True, verbose_name='课程简介')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('material_count', models.IntegerField(default=0, verbose_name='资料数')),
                ('college', models.ForeignKey(blank=True, help_text='通识课无需选择学院', null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.college', verbose_name='所属学院')),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程',
                'ordering': ['-course_type', 'college', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='资料标题')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('file', models.FileField(blank=True, null=True, upload_to='materials/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'ppt', 'pptx', 'zip', 'rar', 'txt', 'md', 'jpg', 'png'])], verbose_name='文件')),
                ('file_size', models.IntegerField(default=0, verbose_name='文件大小(字节)')),
                ('external_link', models.URLField(blank=True, verbose_name='外部链接')),
                ('uploader_name', models.CharField(blank=True, max_length=50, verbose_name='上传者昵称')),
                ('download_count', models.IntegerField(default=0, verbose_name='下载次数')),
                ('is_approved', models.BooleanField(default=True, verbose_name='已审核')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='materials.course', verbose_name='所属课程')),
                ('material_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.materialtype', verbose_name='资料类型')),
            ],
            options={
                'verbose_name': '资料',
                'verbose_name_plural': '资料',
                'ordering': ['-created_at'],
            },
        ),
    ]
