# Generated by Django 6.0.6 on 2026-07-07 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='external_link',
        ),
        migrations.RemoveField(
            model_name='material',
            name='file',
        ),
        migrations.AddField(
            model_name='material',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='原始文件名'),
        ),
        migrations.AddField(
            model_name='material',
            name='file_path',
            field=models.CharField(blank=True, help_text='相对于 data/materials/ 的路径', max_length=500, verbose_name='存储路径'),
        ),
        migrations.AddField(
            model_name='material',
            name='file_type',
            field=models.CharField(blank=True, help_text='pdf/docx/pptx 等', max_length=20, verbose_name='文件类型'),
        ),
    ]
