# Generated by Django 6.0.6 on 2026-07-07 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_remove_material_external_link_remove_material_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='teacher',
            field=models.CharField(blank=True, max_length=100, verbose_name='任课教师'),
        ),
    ]
