# Generated by Django 6.0.6 on 2026-07-08 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_material_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='节点名称')),
                ('icon_class', models.CharField(blank=True, max_length=50, verbose_name='图标类名')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_divider', models.BooleanField(default=False, verbose_name='分隔线')),
                ('is_math_card', models.BooleanField(default=False, verbose_name='数学卡片')),
                ('course_text', models.CharField(blank=True, max_length=50, verbose_name='通配课程代码')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.course', verbose_name='关联课程')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='materials.coursecategory', verbose_name='父节点')),
            ],
            options={
                'verbose_name': '课程导航节点',
                'verbose_name_plural': '课程导航节点',
                'ordering': ['order'],
            },
        ),
    ]
