# Generated by Django 6.0.6 on 2026-07-10 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_material_review_notes_material_review_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='assigned_moderator',
            field=models.ForeignKey(blank=True, help_text='总管理员手动指派，覆盖自动路由。null=按规则路由', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reviews', to=settings.AUTH_USER_MODEL, verbose_name='指派审核人'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='managed_majors',
            field=models.ManyToManyField(blank=True, help_text='小版主仅管理这些专业（学院）对应的课程资料审核', to='materials.college', verbose_name='管辖专业'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('user', '普通用户'), ('sub_moderator', '小版主'), ('moderator', '版主'), ('super_admin', '总管理员')], default='user', max_length=20),
        ),
        migrations.CreateModel(
            name='ReviewComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='异议内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='评论者')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_comments', to='materials.material', verbose_name='关联资料')),
            ],
            options={
                'verbose_name': '审核评论',
                'verbose_name_plural': '审核评论',
                'ordering': ['created_at'],
            },
        ),
    ]
