# Generated by Django 6.0.6 on 2026-07-10 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0006_material_assigned_moderator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_moderate_general',
            field=models.BooleanField(default=False, verbose_name='可审核通识课'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='managed_majors',
            field=models.ManyToManyField(blank=True, help_text='小版主仅管理这些专业（学院）对应的课程资料审核', to='materials.college', verbose_name='管辖专业'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('user', '普通用户'), ('sub_moderator', '小版主'), ('moderator', '版主'), ('super_admin', '总管理员')], default='user', max_length=20),
        ),
    ]
