# Generated by Django 6.0.6 on 2026-07-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0007_userprofile_can_moderate_general_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='auto_approve',
            field=models.BooleanField(default=False, help_text='开启后自动通过管辖板块内所有新上传的资料', verbose_name='自动托管审核'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_auto_approve',
            field=models.BooleanField(default=False, help_text='总管理员设置：该用户是否可以开启自动托管', verbose_name='允许自动托管'),
        ),
    ]
