# Generated by Django 6.0.6 on 2026-07-12 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0008_userprofile_auto_approve_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='course_code',
            field=models.CharField(blank=True, help_text='通知创建时冗余存储，material 删除后仍可导航', max_length=50, verbose_name='课程代码'),
        ),
        migrations.AddField(
            model_name='notification',
            name='course_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='课程名称'),
        ),
        migrations.AddField(
            model_name='reviewcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='materials.reviewcomment', verbose_name='父评论'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='头像'),
        ),
        migrations.CreateModel(
            name='DownloadRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(blank=True, max_length=50, verbose_name='课程代码')),
                ('course_name', models.CharField(blank=True, max_length=200, verbose_name='课程名称')),
                ('material_title', models.CharField(blank=True, max_length=200, verbose_name='资料标题')),
                ('file_name', models.CharField(blank=True, max_length=255, verbose_name='文件名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='下载时间')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.material', verbose_name='关联资料')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_records', to=settings.AUTH_USER_MODEL, verbose_name='下载用户')),
            ],
            options={
                'verbose_name': '下载记录',
                'verbose_name_plural': '下载记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
