# Generated by Django 6.0.6 on 2026-07-13 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0009_notification_course_code_notification_course_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('approved', '审核通过'), ('rejected', '审核驳回'), ('disagree', '审核异议'), ('report', '举报通知'), ('file_deleted', '用户删除资料')], max_length=20, verbose_name='通知类型'),
        ),
        migrations.CreateModel(
            name='DeletionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_id', models.IntegerField(verbose_name='原资料ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('file_name', models.CharField(max_length=500, verbose_name='文件名')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='文件大小')),
                ('course_code', models.CharField(max_length=50, verbose_name='课程代码')),
                ('course_name', models.CharField(max_length=200, verbose_name='课程名称')),
                ('uploader_name', models.CharField(max_length=150, verbose_name='上传者')),
                ('deleted_at', models.DateTimeField(auto_now_add=True, verbose_name='删除时间')),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='删除人')),
            ],
            options={
                'verbose_name': '删除记录',
                'verbose_name_plural': '删除记录',
                'ordering': ['-deleted_at'],
            },
        ),
    ]
