# Generated by Django 6.0.6 on 2026-07-14 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0010_deletion_record'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deletionrecord',
            name='college_id',
            field=models.IntegerField(blank=True, default=None, help_text='冗余字段，用于管理员按管辖范围过滤删除记录', null=True, verbose_name='所属学院ID'),
        ),
        migrations.AddField(
            model_name='deletionrecord',
            name='delete_reason',
            field=models.TextField(blank=True, default='', verbose_name='删除理由'),
        ),
        migrations.AddField(
            model_name='deletionrecord',
            name='is_restored',
            field=models.BooleanField(default=False, verbose_name='已恢复'),
        ),
        migrations.AddField(
            model_name='deletionrecord',
            name='restored_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='恢复时间'),
        ),
        migrations.AddField(
            model_name='deletionrecord',
            name='restored_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restored_deletions', to=settings.AUTH_USER_MODEL, verbose_name='恢复人'),
        ),
        migrations.CreateModel(
            name='FolderOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', '创建'), ('delete', '删除')], max_length=10, verbose_name='操作类型')),
                ('category_id', models.IntegerField(default=0, verbose_name='文件夹ID')),
                ('category_name', models.CharField(blank=True, max_length=200, verbose_name='文件夹名称')),
                ('parent_path', models.CharField(blank=True, help_text='父节点名称序列，用 / 分隔', max_length=500, verbose_name='路径')),
                ('folder_type', models.CharField(blank=True, default='', help_text='normal=普通文件夹 leaf=底层文件夹', max_length=10, verbose_name='文件夹类型')),
                ('reason', models.TextField(blank=True, default='', verbose_name='操作理由')),
                ('is_restored', models.BooleanField(default=False, verbose_name='已撤销')),
                ('restored_at', models.DateTimeField(blank=True, null=True, verbose_name='撤销时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('restored_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restored_operations', to=settings.AUTH_USER_MODEL, verbose_name='撤销人')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '文件夹操作',
                'verbose_name_plural': '文件夹操作',
                'ordering': ['-created_at'],
            },
        ),
    ]
