# Generated by Django 6.0.6 on 2026-07-16 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0011_deletionrecord_college_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, default='', help_text='200字以内', max_length=200, verbose_name='个人简介'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='contact_email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='联系邮箱'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='contact_way',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='联系方式'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('approved', '审核通过'), ('rejected', '审核驳回'), ('disagree', '审核异议'), ('report', '举报通知'), ('file_deleted', '用户删除资料'), ('operation', '操作通知'), ('announcement', '系统公告')], max_length=20, verbose_name='通知类型'),
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='公告标题')),
                ('content', models.TextField(verbose_name='公告内容')),
                ('is_published', models.BooleanField(default=True, verbose_name='已发布')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='发布者')),
            ],
            options={
                'verbose_name': '系统公告',
                'verbose_name_plural': '系统公告',
                'ordering': ['-created_at'],
            },
        ),
    ]
