# Generated by Django 6.0.6 on 2026-08-07 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0014_alter_material_course_coursecreationrequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='token_version',
            field=models.IntegerField(default=0, help_text='改密/重置后 +1，使旧 JWT 立即失效（P2.5）', verbose_name='JWT 令牌版本'),
        ),
    ]
