# Generated by Django 6.0.6 on 2026-08-07 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0015_userprofile_token_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecategory',
            name='is_third_row',
            field=models.BooleanField(default=False, verbose_name='第三行特排卡片'),
        ),
    ]
