# Generated by Django 6.0.6 on 2026-08-08 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0016_coursecategory_is_third_row'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecreationrequest',
            name='auto_approved',
            field=models.BooleanField(default=False, help_text='申请人在自己辖区内提交时直接创建课程文件夹，无需人工审核', verbose_name='管理员辖区内自动通过'),
        ),
    ]
