# Generated by Django 6.0.6 on 2026-08-10 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0018_fix_sta01801_duplicate_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='deletionrecord',
            name='trash_path',
            field=models.CharField(blank=True, default='', help_text='软删除时物理文件移入 data/trash/ 的相对路径（MEDIA_ROOT 相对）；空表示当时文件已不存在。48h 内可据此恢复。', max_length=500, verbose_name='暂存路径'),
        ),
    ]
