# Generated by Django 6.0.6 on 2026-08-11 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0019_deletionrecord_trash_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('approved', '审核通过'), ('rejected', '审核驳回'), ('disagree', '审核异议'), ('report', '举报通知'), ('file_deleted', '用户删除资料'), ('operation', '操作通知'), ('announcement', '系统公告'), ('new_pending', '新待审核')], max_length=20, verbose_name='通知类型'),
        ),
    ]
