# Generated by Django 6.0.6 on 2026-08-11 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0020_alter_notification_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='daily_report_count',
            field=models.IntegerField(default=0, verbose_name='今日已举报'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_report_date',
            field=models.DateField(blank=True, null=True, verbose_name='最后举报日期'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('approved', '审核通过'), ('rejected', '审核驳回'), ('disagree', '审核异议'), ('report', '举报通知'), ('file_deleted', '用户删除资料'), ('operation', '操作通知'), ('announcement', '系统公告'), ('new_pending', '新待审核'), ('report_alert', '新举报待处理'), ('report_result', '举报处理结果'), ('report_escalated', '举报已升级'), ('report_malicious', '恶意举报提醒')], max_length=20, verbose_name='通知类型'),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('material', '资料举报'), ('user', '连带举报用户')], default='material', max_length=10, verbose_name='举报类型')),
                ('reporter_name', models.CharField(blank=True, max_length=50, verbose_name='举报人昵称')),
                ('reasons', models.JSONField(blank=True, default=list, verbose_name='举报原因')),
                ('detail', models.TextField(blank=True, default='', verbose_name='详细说明')),
                ('material_title', models.CharField(blank=True, max_length=200, verbose_name='资料标题')),
                ('course_code', models.CharField(blank=True, max_length=50, verbose_name='课程代码')),
                ('course_name', models.CharField(blank=True, max_length=200, verbose_name='课程名称')),
                ('target_user_name', models.CharField(blank=True, max_length=50, verbose_name='被举报用户昵称')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='举报时间')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('handled', '已处理'), ('escalated', '已升级')], default='pending', max_length=10, verbose_name='状态')),
                ('is_true', models.BooleanField(blank=True, null=True, verbose_name='属实')),
                ('actual_situation', models.TextField(blank=True, default='', verbose_name='实际情况/保留原因')),
                ('action', models.CharField(blank=True, choices=[('delete', '删除'), ('keep', '保留')], max_length=10, null=True, verbose_name='处理方式')),
                ('allow_retry', models.BooleanField(blank=True, null=True, verbose_name='允许重新上传')),
                ('is_malicious', models.BooleanField(blank=True, null=True, verbose_name='恶意举报')),
                ('handled_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('candidates', models.ManyToManyField(blank=True, help_text='举报受理/作用域过滤依据；升级（连带属实）后重设为全部总管理员', related_name='report_candidates', to=settings.AUTH_USER_MODEL, verbose_name='受理候选人')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_reports', to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='materials.material', verbose_name='被举报资料')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_submitted', to=settings.AUTH_USER_MODEL, verbose_name='举报人')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported', to=settings.AUTH_USER_MODEL, verbose_name='被连带举报用户')),
            ],
            options={
                'verbose_name': '举报',
                'verbose_name_plural': '举报',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('kind', 'material')), fields=('reporter', 'material'), name='uniq_material_report'), models.UniqueConstraint(condition=models.Q(('kind', 'user')), fields=('reporter', 'target_user'), name='uniq_user_report')],
            },
        ),
    ]
