# Generated by Django 6.0.6 on 2026-08-11 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0021_userprofile_daily_report_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='material_pk',
            field=models.IntegerField(blank=True, help_text='冗余：材料删除后 FK 置空，此字段保留原始 ID 供聚合/删除联动判断', null=True, verbose_name='被举报资料ID'),
        ),
    ]
