# Generated by Django 6.0.6 on 2026-08-12 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0022_report_material_pk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QaAskClickDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='日期')),
                ('count', models.IntegerField(default=0, verbose_name='当日点击')),
            ],
            options={
                'verbose_name': '问答区提问点击埋点',
                'verbose_name_plural': '问答区提问点击埋点',
            },
        ),
        migrations.CreateModel(
            name='QaTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='标签名')),
                ('icon', models.CharField(blank=True, default='', max_length=50, verbose_name='图标')),
                ('color', models.CharField(blank=True, default='', max_length=20, verbose_name='颜色')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('level', models.IntegerField(choices=[(1, '一级'), (2, '二级')], default=2, verbose_name='级别')),
                ('description', models.CharField(blank=True, default='', help_text='二级标签点击后显示的括号内解释', max_length=200, verbose_name='说明')),
            ],
            options={
                'verbose_name': '问答区标签',
                'verbose_name_plural': '问答区标签',
                'ordering': ['level', 'sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_moderate_qa',
            field=models.BooleanField(default=False, verbose_name='可审核问答区'),
        ),
        migrations.CreateModel(
            name='QaQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('content', models.TextField(max_length=1000, verbose_name='正文（富文本 HTML）')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='置顶')),
                ('pinned_at', models.DateTimeField(blank=True, null=True, verbose_name='置顶时间')),
                ('status', models.CharField(choices=[('published', '已发布'), ('deleted', '已删除'), ('pending', '待审核'), ('rejected', '已驳回')], default='published', max_length=20, verbose_name='状态')),
                ('view_count', models.IntegerField(default=0, verbose_name='浏览量')),
                ('favorite_count', models.IntegerField(default=0, verbose_name='收藏数')),
                ('heat_score', models.IntegerField(default=0, verbose_name='热度分（Phase 2 预留）')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qa_questions', to=settings.AUTH_USER_MODEL)),
                ('tag_l1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='materials.qatag', verbose_name='一级标签')),
                ('tag_l2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='materials.qatag', verbose_name='二级标签')),
            ],
            options={
                'verbose_name': '问答区问题',
                'verbose_name_plural': '问答区问题',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QaAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=20000, verbose_name='回答正文（富文本 HTML）')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='置顶')),
                ('pinned_at', models.DateTimeField(blank=True, null=True, verbose_name='置顶时间')),
                ('like_count', models.IntegerField(default=0, verbose_name='点赞数')),
                ('is_accepted', models.BooleanField(default=False, verbose_name='最佳回答（Phase 2 预留）')),
                ('status', models.CharField(choices=[('published', '已发布'), ('deleted', '已删除'), ('pending', '待审核'), ('rejected', '已驳回')], default='published', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qa_answers', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='materials.qaquestion')),
            ],
            options={
                'verbose_name': '问答区回答',
                'verbose_name_plural': '问答区回答',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QaAnswerLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='点赞时间')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='materials.qaanswer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qa_answer_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '回答点赞',
                'verbose_name_plural': '回答点赞',
                'constraints': [models.UniqueConstraint(fields=('user', 'answer'), name='uniq_qa_answer_like')],
            },
        ),
        migrations.CreateModel(
            name='QaEditHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('question', '问题'), ('answer', '回答')], max_length=10, verbose_name='目标类型')),
                ('target_id', models.PositiveIntegerField(verbose_name='目标ID')),
                ('old_title', models.CharField(blank=True, default='', max_length=100, verbose_name='编辑前标题')),
                ('new_title', models.CharField(blank=True, default='', max_length=100, verbose_name='编辑后标题')),
                ('old_content', models.TextField(blank=True, default='', verbose_name='编辑前正文')),
                ('new_content', models.TextField(blank=True, default='', verbose_name='编辑后正文')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='编辑时间')),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qa_edit_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '问答区编辑历史',
                'verbose_name_plural': '问答区编辑历史',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['target_type', 'target_id'], name='qa_edit_hist_target')],
            },
        ),
        migrations.CreateModel(
            name='QaFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='收藏时间')),
                ('answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qa_favorited_by', to='materials.qaanswer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qa_favorites', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qa_favorited_by', to='materials.qaquestion')),
            ],
            options={
                'verbose_name': '问答区收藏',
                'verbose_name_plural': '问答区收藏',
                'constraints': [models.UniqueConstraint(condition=models.Q(('answer__isnull', False)), fields=('user', 'answer'), name='uniq_qa_fav_answer'), models.UniqueConstraint(condition=models.Q(('answer__isnull', True)), fields=('user', 'question'), name='uniq_qa_fav_question')],
            },
        ),
        migrations.CreateModel(
            name='QaViewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='浏览日期')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_logs', to='materials.qaquestion')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qa_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '问答区浏览日志',
                'verbose_name_plural': '问答区浏览日志',
                'constraints': [models.UniqueConstraint(condition=models.Q(('user__isnull', True)), fields=('question', 'date'), name='uniq_qa_view_guest'), models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'question', 'date'), name='uniq_qa_view_user')],
            },
        ),
    ]
