# Generated by Django 6.0.6 on 2026-08-13 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0025_qa_l1_sort_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['-is_pinned', '-created_at'], 'verbose_name': '资料', 'verbose_name_plural': '资料'},
        ),
        migrations.AddField(
            model_name='material',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='置顶'),
        ),
        migrations.AddField(
            model_name='material',
            name='pinned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='置顶时间'),
        ),
    ]
