# Generated by Django 6.0.6 on 2026-08-16 22:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0026_alter_material_options_material_is_pinned_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_open', models.BooleanField(default=False, verbose_name='普通用户提问/回答开放')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '问答区配置',
                'verbose_name_plural': '问答区配置',
            },
        ),
        migrations.CreateModel(
            name='QaDeleteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('question', '问题'), ('answer', '回答')], max_length=10, verbose_name='目标类型')),
                ('target_id', models.PositiveIntegerField(verbose_name='目标ID')),
                ('reason', models.TextField(max_length=500, verbose_name='删除理由')),
                ('status', models.CharField(choices=[('pending', '待批准'), ('approved', '已批准'), ('rejected', '已驳回')], default='pending', max_length=10, verbose_name='状态')),
                ('auto_approved', models.BooleanField(default=False, verbose_name='简单删除自动批准')),
                ('handled_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
            ],
            options={
                'verbose_name': '问答区删除申请',
                'verbose_name_plural': '问答区删除申请',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='report',
            name='qa_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='materials.qaanswer', verbose_name='被举报回答'),
        ),
        migrations.AddField(
            model_name='report',
            name='qa_answer_pk',
            field=models.IntegerField(blank=True, help_text='冗余：回答删除后 FK 置空，此字段保留原始 ID 供聚合/处理定位', null=True, verbose_name='被举报回答ID'),
        ),
        migrations.AddField(
            model_name='report',
            name='qa_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='materials.qaquestion', verbose_name='被举报问题'),
        ),
        migrations.AddField(
            model_name='report',
            name='qa_question_pk',
            field=models.IntegerField(blank=True, help_text='冗余：问题删除后 FK 置空，此字段保留原始 ID 供聚合/处理定位', null=True, verbose_name='被举报问题ID'),
        ),
        migrations.AddField(
            model_name='report',
            name='qa_question_title',
            field=models.CharField(blank=True, help_text='冗余：问答区举报记被举报问题标题（回答举报记父问题标题），FK 失效后仍可读', max_length=200, verbose_name='问题标题'),
        ),
        migrations.AlterField(
            model_name='report',
            name='kind',
            field=models.CharField(choices=[('material', '资料举报'), ('user', '连带举报用户'), ('question', '问题举报'), ('answer', '回答举报')], default='material', max_length=10, verbose_name='举报类型'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'question')), fields=('reporter', 'qa_question'), name='uniq_qa_question_report'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'answer')), fields=('reporter', 'qa_answer'), name='uniq_qa_answer_report'),
        ),
        migrations.AddField(
            model_name='qaconfig',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qa_config_updates', to=settings.AUTH_USER_MODEL, verbose_name='最近操作人'),
        ),
        migrations.AddField(
            model_name='qadeleterequest',
            name='handled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qa_delreq_handled', to=settings.AUTH_USER_MODEL, verbose_name='处理人'),
        ),
        migrations.AddField(
            model_name='qadeleterequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qa_delete_requests', to=settings.AUTH_USER_MODEL, verbose_name='申请人'),
        ),
        migrations.AddIndex(
            model_name='qadeleterequest',
            index=models.Index(fields=['target_type', 'target_id'], name='qa_delreq_target'),
        ),
        migrations.AddConstraint(
            model_name='qadeleterequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('requester', 'target_type', 'target_id'), name='uniq_qa_delreq_pending'),
        ),
    ]
