# Generated by Django 6.0.6 on 2026-08-16 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0027_qaconfig_qadeleterequest_report_qa_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='identity_college',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='身份学院'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='identity_major',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='身份专业'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='identity_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='身份最近修改时间'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='show_college_public',
            field=models.BooleanField(default=False, verbose_name='公开资料显示学院'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='show_major_public',
            field=models.BooleanField(default=False, verbose_name='公开资料显示专业'),
        ),
    ]
