# Generated by Django 6.0.6 on 2026-09-09 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0035_course_merged_into_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('approved', '审核通过'), ('rejected', '审核驳回'), ('disagree', '审核异议'), ('report', '举报通知'), ('file_deleted', '用户删除资料'), ('operation', '操作通知'), ('announcement', '系统公告'), ('new_pending', '新待审核'), ('report_alert', '新举报待处理'), ('report_result', '举报处理结果'), ('report_escalated', '举报已升级'), ('report_malicious', '恶意举报提醒'), ('merge_alert', '同名课程合并待复核'), ('feedback', '意见反馈')], max_length=20, verbose_name='通知类型'),
        ),
    ]
