# Generated by Django 6.0.7 on 2026-09-09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0036_alter_notification_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableImportRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=64, verbose_name='导入事件编号')),
                ('course_count', models.PositiveIntegerField(default=0, verbose_name='导入课程数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='导入时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_imports', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '课表导入记录',
                'verbose_name_plural': '课表导入记录',
                'ordering': ['-created_at', '-id'],
                'indexes': [
                    models.Index(fields=['created_at'], name='ttimport_created'),
                    models.Index(fields=['user', 'created_at'], name='ttimport_user_created'),
                ],
                'constraints': [
                    models.UniqueConstraint(fields=('user', 'event_id'), name='uniq_ttimport_user_event'),
                ],
            },
        ),
    ]
