# Generated by Django 6.0.6 on 2026-09-13 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0042_alter_userprofile_color_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='专业名称')),
                ('level', models.CharField(choices=[('本科', '本科'), ('硕士', '硕士'), ('博士', '博士')], max_length=10, verbose_name='培养层次')),
                ('track', models.CharField(blank=True, choices=[('academic', '学术学位'), ('professional', '专业学位')], default='', help_text='硕博专用：学术学位/专业学位；本科留空', max_length=20, verbose_name='学位类型')),
                ('code', models.CharField(blank=True, default='', help_text='硕博一级学科/专业学位类别代码（如 0101、0451），便于后续对接', max_length=10, verbose_name='学科代码')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, help_text='停用后不再出现在身份标签选项中，但保留历史数据与匹配能力', verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='majors', to='materials.college', verbose_name='学院')),
            ],
            options={
                'verbose_name': '专业',
                'verbose_name_plural': '专业',
                'ordering': ['order', 'id'],
                'indexes': [models.Index(fields=['level', 'is_active'], name='materials_m_level_888e77_idx')],
                'constraints': [models.UniqueConstraint(fields=('college', 'name', 'level'), name='uniq_major_college_name_level')],
            },
        ),
    ]
