# Generated by Django 6.0.6 on 2026-09-13 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0046_remove_sanzhixuanxiang_legacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='campus',
            field=models.CharField(choices=[('北京', '北京校区'), ('珠海', '珠海校区')], default='北京', help_text='仅作内部归属标注（身份标签不区分校区）；珠海学院以 2026 招生目录核实为准', max_length=10, verbose_name='校区'),
        ),
    ]
