# Generated by Django 6.0.6 on 2026-09-14 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0049_userprofile_timetable_text_align'),
    ]

    operations = [
        migrations.AddField(
            model_name='major',
            name='department',
            field=models.CharField(blank=True, default='', help_text='学院内部系建制（如文理学院中文系）；本科下拉按系 optgroup 分组，无系建制的学院留空', max_length=50, verbose_name='所属系'),
        ),
    ]
