# Generated by Django 6.0.6 on 2026-09-16 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0051_monitoring_query_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granularity', models.CharField(choices=[('hour', '小时'), ('day', '日')], max_length=5, verbose_name='聚合粒度')),
                ('bucket_start', models.DateTimeField(verbose_name='桶起点')),
                ('event_name', models.CharField(choices=[('auth.login.success', '登录成功'), ('auth.login.failure', '登录失败'), ('view.open', '页面打开'), ('search.execute', '执行搜索'), ('search.no_result', '搜索无结果'), ('material.preview.success', '预览成功'), ('material.preview.failure', '预览失败'), ('material.download.success', '下载成功'), ('material.download.quota_denied', '下载配额拒绝'), ('material.download.failure', '下载失败'), ('material.upload.success', '上传成功'), ('material.upload.failure', '上传失败'), ('timetable.import.success', '课表导入成功'), ('timetable.import.failure', '课表导入失败'), ('moderation.decision', '审核决定')], max_length=48, verbose_name='事件名称')),
                ('audience', models.CharField(choices=[('user', '登录用户'), ('anonymous', '匿名访客')], max_length=12, verbose_name='主体类型')),
                ('event_count', models.PositiveIntegerField(default=0, verbose_name='事件次数')),
                ('people_count', models.PositiveIntegerField(default=0, verbose_name='去重人数')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '监测行为聚合',
                'verbose_name_plural': '监测行为聚合',
                'indexes': [models.Index(fields=['granularity', 'bucket_start'], name='mon_agg_gran_bucket'), models.Index(fields=['event_name', 'bucket_start'], name='mon_agg_event_bucket')],
                'constraints': [models.UniqueConstraint(fields=('granularity', 'bucket_start', 'event_name', 'audience'), name='uniq_mon_aggregate_bucket_event_audience')],
            },
        ),
        migrations.CreateModel(
            name='MonitoringEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=80, unique=True, verbose_name='事件编号')),
                ('event_name', models.CharField(choices=[('auth.login.success', '登录成功'), ('auth.login.failure', '登录失败'), ('view.open', '页面打开'), ('search.execute', '执行搜索'), ('search.no_result', '搜索无结果'), ('material.preview.success', '预览成功'), ('material.preview.failure', '预览失败'), ('material.download.success', '下载成功'), ('material.download.quota_denied', '下载配额拒绝'), ('material.download.failure', '下载失败'), ('material.upload.success', '上传成功'), ('material.upload.failure', '上传失败'), ('timetable.import.success', '课表导入成功'), ('timetable.import.failure', '课表导入失败'), ('moderation.decision', '审核决定')], max_length=48, verbose_name='事件名称')),
                ('audience', models.CharField(choices=[('user', '登录用户'), ('anonymous', '匿名访客')], max_length=12, verbose_name='主体类型')),
                ('actor_hash', models.CharField(blank=True, default='', max_length=64, verbose_name='匿名主体摘要')),
                ('day', models.DateField(db_index=True, verbose_name='本地日期')),
                ('occurred_at', models.DateTimeField(db_index=True, verbose_name='发生时间')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='接收时间')),
                ('view_name', models.CharField(blank=True, default='', max_length=40, verbose_name='规范化视图')),
                ('outcome', models.CharField(blank=True, default='', max_length=24, verbose_name='低基数结果')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitoring_events', to=settings.AUTH_USER_MODEL, verbose_name='登录用户')),
            ],
            options={
                'verbose_name': '监测行为事件',
                'verbose_name_plural': '监测行为事件',
                'indexes': [models.Index(fields=['event_name', 'day'], name='mon_event_name_day'), models.Index(fields=['audience', 'day'], name='mon_audience_day'), models.Index(fields=['day', 'occurred_at'], name='mon_day_occurred'), models.Index(fields=['user', 'day'], name='mon_user_day')],
            },
        ),
    ]
