# Generated by Django 6.0.6 on 2026-09-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0052_monitoringaggregate_monitoringevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="view_count",
            field=models.PositiveIntegerField(default=0, verbose_name="浏览量"),
        ),
    ]
