# Generated by Django 6.0.6 on 2026-09-20 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0053_material_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertimetable',
            name='revision',
            field=models.PositiveIntegerField(default=0, verbose_name='修订号'),
        ),
    ]
