# Generated by Django 6.0.6 on 2026-09-20 00:30
#
# 人工补充：AddConstraint（uniq_notif_approved_per_material）之前先去重
# 存量 approved 通知——历史补发可能给同一人同一资料留下多条，不去重迁移
# 会在生产数据上直接失败。保留每组最早一条（ID 最小），其余删除；
# 同组内容语义相同（同人同资料的通过通知），删除无信息损失。

from django.conf import settings
from django.db import migrations, models
from django.db.models import Count, Min


def dedupe_approved_notifications(apps, schema_editor):
    Notification = apps.get_model('materials', 'Notification')
    dup_groups = (Notification.objects
                  .filter(type='approved', material__isnull=False)
                  .values('recipient_id', 'material_id')
                  .annotate(min_id=Min('id'), total=Count('id'))
                  .filter(total__gt=1))
    for g in dup_groups:
        Notification.objects.filter(
            type='approved',
            recipient_id=g['recipient_id'],
            material_id=g['material_id'],
        ).exclude(id=g['min_id']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0054_usertimetable_revision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['code'], name='course_code_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read', 'created_at'], name='notif_recip_read_created'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'material', 'type'], name='notif_recip_material_type'),
        ),
        migrations.RunPython(dedupe_approved_notifications, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(condition=models.Q(('material__isnull', False), ('type', 'approved')), fields=('recipient', 'material'), name='uniq_notif_approved_per_material'),
        ),
    ]
