# Generated by Django 6.0.6 on 2026-09-21

from django.db import migrations, models
from django.utils import timezone


def mark_existing_uploaders(apps, schema_editor):
    UserProfile = apps.get_model("materials", "UserProfile")
    Material = apps.get_model("materials", "Material")
    uploader_ids = Material.objects.filter(
        uploader_id__isnull=False,
    ).values_list("uploader_id", flat=True).distinct()
    UserProfile.objects.filter(
        user_id__in=uploader_ids,
        first_upload_email_sent_at__isnull=True,
    ).update(first_upload_email_sent_at=timezone.now())


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0055_course_course_code_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="first_upload_email_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="首份资料感谢邮件成功发送后记录；空值允许失败后重试",
                null=True,
                verbose_name="首份资料感谢邮件发送时间",
            ),
        ),
        migrations.RunPython(mark_existing_uploaders, migrations.RunPython.noop),
    ]
